Legge til støtte for sikring med token fra Azure AD
navikt/bidrag-dokument pull request #316
Opened 2021-01-13 08:38 UTC by s148719

2021-01-13 16:43 UTC, jactor-rises commented on pom.xml
> +
linje 196? kav vi slå av downgrade ac nimbus når vi fjerner isso?

2021-01-13 17:50 UTC, jactor-rises commented
det er mange endringer i koden som bare er kodeformatering... dette må fikses

2021-01-13 17:54 UTC, jactor-rises commented on src/main/java/no/nav/bidrag/dokument/BidragDokument.java
> -@EnableJwtTokenValidation(ignore = {"springfox.documentation.swagger.web.ApiResourceController"})
bra at den sammen med oauth annotering er flyttet til config klassen

2021-01-13 17:58 UTC, jactor-rises commented on src/main/java/no/nav/bidrag/dokument/BidragDokumentConfig.java
> -        .map(tokenValidationContext -> tokenValidationContext.getJwtTokenAsOptional(ISSUER))
bra at vi slipper ISSUER argument når vi henter token

2021-01-13 18:03 UTC, jactor-rises commented on src/main/java/no/nav/bidrag/dokument/consumer/BidragArkivConsumer.java
> +            .toUriString();
en typisk formateringsfeil... verifiser kodeformat og reformater

2021-01-13 18:04 UTC, jactor-rises commented on src/main/java/no/nav/bidrag/dokument/consumer/BidragArkivConsumer.java
> +            .toUriString();
sørg for å reformater samtlige filer du har endret

2021-01-13 18:10 UTC, jactor-rises commented on src/main/java/no/nav/bidrag/dokument/BidragDokumentConfig.java
> +  @Autowired private ClientConfigurationProperties clientConfigurationProperties;
linjeskift mellom statiske felt og @Autowired variabel

2021-01-13 18:18 UTC, jactor-rises commented on src/test/java/no/nav/bidrag/dokument/consumer/BidragArkivConsumerTest.java
> +  @Mock ConsumerTarget consumerTarget;
dette er en spring-context test. hvorfor må du moske consumerTarget?
det blir veldig mye koding som bare er mocking (og derfor sterkt kobler test med implementasjon)
I tillegg blir det mange kodelinjer ettersom riktig formatering ikke vil godta annotering og deklarasjon av variabler på samme linje (med unntak av parameter)

2021-01-13 18:20 UTC, jactor-rises commented on src/test/java/no/nav/bidrag/dokument/consumer/BidragArkivConsumerTest.java
> +    when(consumerTarget.getBaseUrl()).thenReturn("bidrag-dokument-arkiv-url");
igjen... hvorfor må denne mockes?....

2021-01-13 18:23 UTC, jactor-rises commented on src/test/java/no/nav/bidrag/dokument/controller/DokumentControllerTest.java
> +  @MockBean private RestTemplateProvider restTemplateProviderMock;
spring-test... hvorfor moske denne?

2021-01-13 18:25 UTC, jactor-rises commented on src/test/java/no/nav/bidrag/dokument/controller/DokumentControllerTest.java
> +                DokumentTilgangResponse.class));
formatering...

2021-01-13 18:25 UTC, jactor-rises commented on src/test/java/no/nav/bidrag/dokument/controller/DokumentControllerTest.java
> +                            .isEqualTo(new DokumentTilgangResponse("urlWithToken", "BREVLAGER"))));
formatering

2021-01-13 18:26 UTC, jactor-rises requested changes
unødig mocking? ...og kodeformatering som må fikses

2021-01-13 20:18 UTC, s148719 commented on pom.xml
> +
Tror ikke det er isso-spesifikt, men downgrade behovet kan forsvinne plutselig, så kan verifisere etter hvert

2021-01-13 20:21 UTC, s148719 commented
> det er mange endringer i koden som bare er kodeformatering... verifiser kodeformatering på koden

Har brukt Google format i Intellij, ser du eksempler på feil formatering, eller reagerer du bare på at filer har blitt reformatert? Om du ikke ser feil, kan det vel hende filene tidligere er endret uten at google formatering har kjørt?

2021-01-13 20:31 UTC, s148719 commented on src/main/java/no/nav/bidrag/dokument/consumer/BidragArkivConsumer.java
> +            .toUriString();
ser IDE-en min var helt default Google format, altså med hard wrap at 100 i stedet for 150.. Får gå igjennom med 150

2021-01-13 20:33 UTC, s148719 commented on src/main/java/no/nav/bidrag/dokument/BidragDokumentConfig.java
> -        .map(tokenValidationContext -> tokenValidationContext.getJwtTokenAsOptional(ISSUER))
Ja, skal aldri være mer enn ett token i header på en request, så trenger ikke å hente ut etter issuer

2021-01-13 20:34 UTC, s148719 commented on src/main/java/no/nav/bidrag/dokument/BidragDokumentConfig.java
> +  @Autowired private ClientConfigurationProperties clientConfigurationProperties;
hmm, får importere google-format.xml-en fra bidrag-dev igjen

2021-01-13 20:53 UTC, s148719 commented on src/test/java/no/nav/bidrag/dokument/controller/DokumentControllerTest.java
> +  @MockBean private RestTemplateProvider restTemplateProviderMock;
hmm, skjuler kanskje et reelt problem, må sjekke

2021-01-13 21:13 UTC, s148719 commented on src/test/java/no/nav/bidrag/dokument/consumer/BidragArkivConsumerTest.java
> +  @Mock ConsumerTarget consumerTarget;
Ser ikke noen vei utenom, får NPE hvis mockene ikke er med

2021-01-14 06:05 UTC, s148719 commented on src/test/java/no/nav/bidrag/dokument/consumer/BidragArkivConsumerTest.java
> +    when(consumerTarget.getBaseUrl()).thenReturn("bidrag-dokument-arkiv-url");
NPE uten

2021-01-14 06:22 UTC, s148719 commented on src/main/java/no/nav/bidrag/dokument/consumer/BidragArkivConsumer.java
> +            .toUriString();
Får samme resultat med linjeknekk på 150, har importert GoogleStyle.xml fra bidrag-dev

2021-01-14 07:42 UTC, s148719 commented on src/main/java/no/nav/bidrag/dokument/BidragDokumentConfig.java
> +  @Autowired private ClientConfigurationProperties clientConfigurationProperties;
har avinstallert google-code-formatter-plugin-en, linjeskift er nå OK, men linjeskift mellom statiske felt og @Autowired legges ikke inn

2021-01-14 07:44 UTC, s148719 commented on src/main/java/no/nav/bidrag/dokument/consumer/BidragArkivConsumer.java
> +            .toUriString();
OK nå etter fjerning av google-code-formatter-plugin

2021-01-14 15:11 UTC, jactor-rises commented on src/main/java/no/nav/bidrag/dokument/BidragDokumentConfig.java
> +  @Autowired private ClientConfigurationProperties clientConfigurationProperties;
nei... jeg ber deg om å legge inn det 😄

2021-01-14 15:15 UTC, jactor-rises commented
set d er problemer med å bygge docker image over hele fjøla... fra slack:

> Andre Roaldseth:house_with_garden:  41 minutes ago
> Løsninga til github: kjør pushen i loop :upsidedowntears:

Kanskje du bør endre GitHub workflow?

2021-01-14 18:24 UTC, jactor-rises commented
jeg foreslår en ny implementasjon eller bruk av `ConsumerTarget`

Det kan ikke være slik at baseurl skal gies i consumer klassene. Nedenstående metode må bort. det eneste `ConsumerTarget` skal bry seg om er å finne riktig `RestTemplate`...

```java
  private RestTemplate henteRestTemplateForToken() {
    var baseurl = consumerTarget.getBaseUrl();
    return consumerTarget.getRestTemplateProvider().provideRestTemplate(KLIENTNAVN_BIDRAG_DOKUMENT_JOURNALPOST, consumerTarget.getBaseUrl());
  }
```

2021-01-19 08:22 UTC, jactor-rises commented on pom.xml
> +    </dependency>
hvorfor har du lagt inn junit 4?

2021-01-19 09:13 UTC, jactor-rises commented on src/main/java/no/nav/bidrag/dokument/controller/JournalpostController.java
> +    return respons;
endre denne tilbake siden du er ferdig med debug

2021-01-19 09:14 UTC, jactor-rises commented on src/main/java/no/nav/bidrag/dokument/service/JournalpostService.java
> +    return respons;
debug? endre tilbake...

2021-01-19 09:15 UTC, jactor-rises commented on src/main/resources/application.yaml
> +# default port for tester som ikke bruker wiremock
som bruker eller ikke bruker?

2021-01-19 09:18 UTC, jactor-rises commented on src/test/java/no/nav/bidrag/dokument/consumer/BidragArkivConsumerTest.java
> -    var journalpostResponse = httpResponse.fetchBody().orElseThrow(() -> new AssertionError("BidragArkivConsumer kunne ikke finne journalpost!"));
her er gullet... all ☝🏻  denne mockinga blir bort 👍🏻

2021-01-19 09:21 UTC, jactor-rises commented on src/test/java/no/nav/bidrag/dokument/consumer/BidragJournalpostConsumerTest.java
>  @SpringBootTest(classes = {BidragDokumentLocal.class}, webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
jeg regner med at siden den bruker RANDOM_PORT at kommentaren om ikke bruk av wiremock er riktig... men hvorfor må dette inn i noe konfigurasjon? jeg kan ikke se at den blir brukt noe sted...

2021-01-19 09:24 UTC, jactor-rises commented on src/test/resources/stubrespons/bdj-hent-tilgang-respons.json
> +  ]
linjeskift...

2021-01-19 09:24 UTC, jactor-rises commented on src/test/resources/stubrespons/journalpostInnholdMidlertidig.json
> +}
linjeskift

2021-01-19 09:28 UTC, jactor-rises requested changes
noe småplukk...
hvorfor innførte du junit 4?
foreslår også at du gir stubben et nytt navn siden du gjenbruker den i flere consumer-klasser... Hvorfor ikke bare kalle den `ConsumerStub`?

2021-01-21 13:30 UTC, s148719 commented on src/main/java/no/nav/bidrag/dokument/controller/JournalpostController.java
> +    return respons;
takk, burde markert den bedre, lett å glemme

2021-01-21 13:32 UTC, s148719 commented
Ja, tenkte på at et mer generisk navn vil være bedre

2021-01-21 13:41 UTC, s148719 commented on src/test/java/no/nav/bidrag/dokument/consumer/BidragJournalpostConsumerTest.java
>  @SpringBootTest(classes = {BidragDokumentLocal.class}, webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
TestRestTemplate skytes ikke inn i kontekst dersom webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT) mangler.

2021-01-21 13:43 UTC, s148719 commented on src/main/resources/application.yaml
> +# default port for tester som ikke bruker wiremock
som ikke bruker, wiremock.server.port settes automatisk av wiremock for tester som bruker wiremock (inneholder @AutoConfigureWireMock(port = 0)-annoteringen) - For tester som ikke bruker wiremock må det settes en verdi for wiremock.server.port manuelt (som det blir gjort under kommentaren du viser til)

2021-01-21 13:45 UTC, s148719 commented on pom.xml
> +    </dependency>
Husker ikke hvorfor, prøver å fjerne

2021-01-21 19:02 UTC, jactor-rises approved these changes

2021-01-21 19:07 UTC, merged